import Logo from "../assets/logo.svg";

export const MyInformation = {
  toolbarData: {
    logoLetters: "John",
    resumeLink: "https://www.lipsum.com/",
    linkedInUrl: "https://www.lipsum.com/",
    instaGramUrl: "https://www.lipsum.com/",
    gitHubUrl: "https://www.lipsum.com/",
  },
  overviewData: {
    intro: "Hi, my name is",
    name: "John Doe",
    summaryHeader: "This is my super attractive summary.",
    summaryDetails:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
  },
  skillsData: {
    skillHeader: "Technical Skills",
    skillsList: [
      { name: "Skill 1", logo: Logo },
      { name: "Skill 2", logo: Logo },
      { name: "Skill 3", logo: Logo },
      { name: "Skill 4", logo: Logo },
      { name: "Skill 5", logo: Logo },
      { name: "Skill 6", logo: Logo },
    ],
  },
  projectsData: {
    header: "My Projects",
    Project_List: [
      {
        name: "Project One",
        date: "01 January 2022",
        logo: Logo,
        logoRound: true,
        overview: "Give an Overview here",
        contributions: [
          "Contributon 1",
          "Contributon 2",
          "Contributon 3",
          "Contributon 4",
        ],
        projectLink: "https://www.lipsum.com/",
        websitelink: "https://www.lipsum.com/",
        technologies: ["Tech used 1", "Tech used 2", "Tech used 3"],
      },
      {
        name: "Project Two",
        date: "01 January 2023",
        logo: Logo,
        logoRound: true,
        overview: "Give an Overview here",
        contributions: [
          "Contributon 1",
          "Contributon 2",
          "Contributon 3",
          "Contributon 4",
        ],
        projectLink: "https://www.lipsum.com/",
        websitelink: "",
        technologies: ["Tech used 1", "Tech used 2", "Tech used 3"],
      },
      {
        name: "Project Three",
        date: "01 January 2024",
        logo: Logo,
        logoRound: true,
        overview: "Give an Overview here",
        contributions: [
          "Contributon 1",
          "Contributon 2",
          "Contributon 3",
          "Contributon 4",
        ],
        projectLink: "",
        websitelink: "https://www.lipsum.com/",
        technologies: ["Tech used 1", "Tech used 2", "Tech used 3"],
      },
    ],
  },
  // timeLineData: {
  //   header: "Timeline",
  //   timeLineImage: Logo,
  // },
  aboutMeData: {
    header: "About Me",
    myPicture: Logo,
    details: [
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    ],
  },
  certificatesData: {
    header: "Certifications",
    certificates: [
      {
        name: "Certificate Name 1",
        programName: "Program Name 1",
        date: "Jan 2022",
        expires: "Jan 2023",
        cid: "Certificate ID 1",
        logo: Logo,
        link: "",
      },
      {
        name: "Certificate Name 2",
        programName: "Program Name 2",
        date: "Jan 2022",
        expires: "Jan 2023",
        cid: "Certificate ID 2",
        logo: Logo,
        link: "",
      },
      {
        name: "Certificate Name 3",
        programName: "Program Name 1",
        date: "Jan 2022",
        expires: "Jan 2023",
        cid: "Certificate ID 1",
        logo: Logo,
        link: "",
      },
      {
        name: "Certificate Name 4",
        programName: "Program Name 2",
        date: "Jan 2022",
        expires: "Jan 2023",
        cid: "Certificate ID 2",
        logo: Logo,
        link: "",
      },
      {
        name: "Certificate Name 5",
        programName: "Program Name 2",
        date: "Jan 2022",
        expires: "Jan 2023",
        cid: "Certificate ID 2",
        logo: Logo,
        link: "",
      },
      {
        name: "Certificate Name 6",
        programName: "Program Name 2",
        date: "Jan 2022",
        expires: "Jan 2023",
        cid: "Certificate ID 2",
        logo: Logo,
        link: "",
      },
    ],
  },
  testimonialsData: {
    TestimonialsList: [
      {
        picture: Logo,
        name: "Recommender 1 Name",
        designation: "Position 1",
        date: "Date",
        relation: "Relationship",
        recommendation:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      },
      {
        picture: Logo,
        name: "Recommender 2 Name ",
        designation: "Position 2",
        date: "Date",
        relation: "Relationship",
        recommendation:
          "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      },
    ],
  },
  footerData: {
    linkedInUrl: "",
    emailId: "mail@gmail.com",
  },
};
